# Generated by Django 3.0.3 on 2020-07-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_cagetory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='imgae',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='cagetory',
            new_name='category',
        ),
    ]
